# Generated by Django 3.1.5 on 2021-02-15 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffees', '0002_auto_20210215_1508'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Roaster',
        ),
    ]
